package handlers_test

import (
	"context"
	"database/sql"
	"encoding/json"
	"net/http"
	"net/http/httptest"
	"path/filepath"
	"strings"
	"testing"
	"time"

	"audiobookshelf-go/internal/database"
	"audiobookshelf-go/internal/repository"
	"audiobookshelf-go/internal/router"
	"audiobookshelf-go/internal/services"

	"github.com/gin-gonic/gin"
	"github.com/golang-jwt/jwt/v5"
	"github.com/google/uuid"
)

const testSecret = "login-fixture-signing-secret"

func loginFixture(t *testing.T) (*sql.DB, *gin.Engine) {
	t.Helper()
	path := filepath.Join(t.TempDir(), "absdatabase.sqlite")
	fixture, err := sql.Open("sqlite", path)
	if err != nil {
		t.Fatal(err)
	}
	// Hashes were generated by the repository's Node bcryptjs at cost 8.
	_, err = fixture.Exec(`CREATE TABLE users (
		id UUID PRIMARY KEY, username VARCHAR(255), pash VARCHAR(255),
		type VARCHAR(255), isActive TINYINT(1)
	);
	CREATE TABLE sessions (
		id UUID PRIMARY KEY, userId UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
		ipAddress VARCHAR(255), userAgent VARCHAR(255), refreshToken VARCHAR(255) NOT NULL,
		expiresAt DATETIME NOT NULL, createdAt DATETIME NOT NULL, updatedAt DATETIME NOT NULL,
		lastRefreshToken VARCHAR(255), lastRefreshTokenExpiresAt DATETIME
	);
	CREATE TABLE settings (key VARCHAR(255) PRIMARY KEY, value JSON);
	INSERT INTO settings VALUES ('server-settings', '{"tokenSecret":"login-fixture-signing-secret"}');
	INSERT INTO users VALUES ('active-id', 'Ryan', '$2a$08$abcdefghijklmnopqrstuuyaaNhTS7DZ3N3oHnoSVa5CQs21UI04C', 'user', 1);
	INSERT INTO users VALUES ('inactive-id', 'inactive', '$2a$08$abcdefghijklmnopqrstuuyaaNhTS7DZ3N3oHnoSVa5CQs21UI04C', 'user', 0);
	INSERT INTO users VALUES ('root-id', 'root', NULL, 'root', 1);
	INSERT INTO users VALUES ('no-hash-id', 'nohash', '', 'user', 1);
	INSERT INTO users VALUES ('bad-hash-id', 'badhash', 'malformed', 'user', 1);
	INSERT INTO users VALUES ('unicode-id', 'unicode', '$2a$08$abcdefghijklmnopqrstuu7CqSGNC8768B7bMJka95hD3ZQ7Kd5dW', 'user', 1);`)
	fixture.Close()
	if err != nil {
		t.Fatal(err)
	}
	db, err := database.OpenSQLite(context.Background(), path)
	if err != nil {
		t.Fatal(err)
	}
	t.Cleanup(func() { db.Close() })
	secret, err := repository.LoadJWTSecret(context.Background(), db)
	if err != nil {
		t.Fatal(err)
	}
	auth, err := services.NewAuthService(repository.NewUserRepository(db),
		repository.NewSessionRepository(db), secret, time.Hour, 30*24*time.Hour)
	if err != nil {
		t.Fatal(err)
	}
	return db, router.New(auth)
}

func postLogin(r *gin.Engine, body, contentType, returnTokens, protocol, target string) *httptest.ResponseRecorder {
	request := httptest.NewRequest(http.MethodPost, target, strings.NewReader(body))
	request.Header.Set("Content-Type", contentType)
	request.Header.Set("User-Agent", "login-test")
	request.Header.Set("x-return-tokens", returnTokens)
	request.Header.Set("x-forwarded-proto", protocol)
	response := httptest.NewRecorder()
	r.ServeHTTP(response, request)
	return response
}

func sessionCount(t *testing.T, db *sql.DB) int {
	t.Helper()
	var count int
	if err := db.QueryRow(`SELECT count(*) FROM sessions`).Scan(&count); err != nil {
		t.Fatal(err)
	}
	return count
}

func tokenClaims(t *testing.T, value, kind, userID string) jwt.MapClaims {
	t.Helper()
	token, err := jwt.Parse(value, func(token *jwt.Token) (any, error) {
		return []byte(testSecret), nil
	}, jwt.WithValidMethods([]string{"HS256"}), jwt.WithExpirationRequired())
	if err != nil || !token.Valid {
		t.Fatalf("invalid %s JWT: %v", kind, err)
	}
	claims := token.Claims.(jwt.MapClaims)
	if claims["type"] != kind || claims["userId"] != userID {
		t.Fatalf("unexpected %s claims: %v", kind, claims)
	}
	id, err := uuid.Parse(claims["jti"].(string))
	if err != nil || id.Version() != 4 {
		t.Fatalf("expected UUIDv4 jti: %v", claims["jti"])
	}
	lifetime := float64(3600)
	if kind == "refresh" {
		lifetime = 30 * 24 * 3600
	}
	if claims["exp"].(float64)-claims["iat"].(float64) != lifetime {
		t.Fatalf("unexpected %s lifetime: %v", kind, claims)
	}
	return claims
}

func checkSuccessfulLogin(t *testing.T, db *sql.DB, response *httptest.ResponseRecorder, headerMode, secure bool) {
	t.Helper()
	var payload struct {
		User struct {
			ID, Username, Type, AccessToken string
			IsActive                        bool
			RefreshToken                    *string
		}
	}
	if err := json.Unmarshal(response.Body.Bytes(), &payload); err != nil {
		t.Fatal(err)
	}
	if !payload.User.IsActive || payload.User.Username == "" || payload.User.Type == "" {
		t.Fatalf("missing basic user fields: %s", response.Body)
	}
	for _, forbidden := range []string{"pash", "password", "tokenSecret", testSecret} {
		if strings.Contains(response.Body.String(), forbidden) {
			t.Fatalf("response exposes %s", forbidden)
		}
	}
	access := tokenClaims(t, payload.User.AccessToken, "access", payload.User.ID)
	if access["username"] != payload.User.Username {
		t.Fatal("JWT username should retain the stored spelling")
	}
	refresh := ""
	cookies := response.Result().Cookies()
	if headerMode {
		if payload.User.RefreshToken == nil || len(cookies) != 0 {
			t.Fatal("header mode must return a refresh token without cookies")
		}
		refresh = *payload.User.RefreshToken
	} else {
		if payload.User.RefreshToken != nil || len(cookies) != 1 {
			t.Fatal("cookie mode must return null refreshToken and one cookie")
		}
		cookie := cookies[0]
		if cookie.Name != "refresh_token" || cookie.Path != "/" || !cookie.HttpOnly ||
			cookie.SameSite != http.SameSiteLaxMode || cookie.Secure != secure || cookie.MaxAge != 30*24*3600 {
			t.Fatalf("unexpected refresh cookie: %+v", cookie)
		}
		refresh = cookie.Value
	}
	refreshClaims := tokenClaims(t, refresh, "refresh", payload.User.ID)
	if refreshClaims["jti"] == access["jti"] {
		t.Fatal("access and refresh credentials must have distinct IDs")
	}
	var id, userID, ip, agent, created, updated, expires string
	var previous, previousExpiry sql.NullString
	if err := db.QueryRow(`SELECT id, userId, ipAddress, userAgent, CAST(createdAt AS TEXT),
		CAST(updatedAt AS TEXT), CAST(expiresAt AS TEXT), lastRefreshToken, lastRefreshTokenExpiresAt
		FROM sessions WHERE refreshToken = ?`, refresh).Scan(
		&id, &userID, &ip, &agent, &created, &updated, &expires, &previous, &previousExpiry,
	); err != nil {
		t.Fatal(err)
	}
	if userID != payload.User.ID || ip != "192.0.2.1" || agent != "login-test" ||
		created != updated || previous.Valid || previousExpiry.Valid {
		t.Fatal("stored session does not match the login")
	}
	if _, err := uuid.Parse(id); err != nil {
		t.Fatal("invalid session ID")
	}
	expiresAt, err := time.Parse("2006-01-02 15:04:05.000 -07:00", expires)
	if err != nil || expiresAt.Unix() != int64(refreshClaims["exp"].(float64)) {
		t.Fatalf("session and token expiry disagree: %q (%v)", expires, err)
	}
}

func TestLoginCredentials(t *testing.T) {
	db, r := loginFixture(t)
	for _, tc := range []struct {
		name, body, contentType string
		status                  int
	}{
		{"mixed-case username", `{"username":"rYaN","password":"test-password"}`, "application/json", 200},
		{"wrong password", `{"username":"Ryan","password":"wrong"}`, "application/json", 401},
		{"unknown user", `{"username":"missing","password":"test-password"}`, "application/json", 401},
		{"inactive user", `{"username":"inactive","password":"test-password"}`, "application/json", 401},
		{"missing username", `{"password":"test-password"}`, "application/json", 400},
		{"empty username", `{"username":"","password":"test-password"}`, "application/json", 400},
		{"missing password", `{"username":"root"}`, "application/json", 400},
		{"null password", `{"username":"root","password":null}`, "application/json", 400},
		{"wrong field type", `{"username":3,"password":"test-password"}`, "application/json", 400},
		{"malformed JSON", `{`, "application/json", 400},
		{"passwordless root", `{"username":"ROOT","password":""}`, "application/json", 200},
		{"root nonempty password", `{"username":"root","password":"wrong"}`, "application/json", 401},
		{"nonroot without hash", `{"username":"nohash","password":""}`, "application/json", 401},
		{"invalid stored hash", `{"username":"badhash","password":"test-password"}`, "application/json", 401},
		{"Unicode password", `{"username":"unicode","password":"pässword密码"}`, "application/json", 200},
		{"form login", "username=RYAN&password=test-password", "application/x-www-form-urlencoded", 200},
		{"form empty root password", "username=root&password=", "application/x-www-form-urlencoded", 200},
		{"form missing password", "username=root", "application/x-www-form-urlencoded", 400},
		{"unsupported content type", "Ryan:test-password", "text/plain", 415},
	} {
		t.Run(tc.name, func(t *testing.T) {
			before := sessionCount(t, db)
			response := postLogin(r, tc.body, tc.contentType, "", "", "http://example.test/login")
			if response.Code != tc.status {
				t.Fatalf("status %d, want %d: %s", response.Code, tc.status, response.Body)
			}
			wantSessions := before
			if tc.status == 200 {
				wantSessions++
				checkSuccessfulLogin(t, db, response, false, false)
			} else if strings.Contains(response.Body.String(), "accessToken") || len(response.Result().Cookies()) != 0 {
				t.Fatal("failed login returned credentials")
			}
			if got := sessionCount(t, db); got != wantSessions {
				t.Fatalf("sessions=%d, want %d", got, wantSessions)
			}
		})
	}
}

func TestLoginTokenTransport(t *testing.T) {
	db, r := loginFixture(t)
	for _, tc := range []struct {
		name, header, protocol, target string
		headerMode, secure             bool
	}{
		{"return tokens", "true", "", "http://example.test/login", true, false},
		{"header is case sensitive", "True", "", "http://example.test/login", false, false},
		{"TLS cookie", "", "", "https://example.test/login", false, true},
		{"forwarded HTTPS cookie", "", "http, HTTPS", "http://example.test/login", false, true},
	} {
		t.Run(tc.name, func(t *testing.T) {
			response := postLogin(r, `{"username":"Ryan","password":"test-password"}`,
				"application/json", tc.header, tc.protocol, tc.target)
			if response.Code != 200 {
				t.Fatalf("login failed: %s", response.Body)
			}
			checkSuccessfulLogin(t, db, response, tc.headerMode, tc.secure)
		})
	}
}

func TestLoginSessionWriteFailure(t *testing.T) {
	db, r := loginFixture(t)
	if _, err := db.Exec(`DROP TABLE sessions`); err != nil {
		t.Fatal(err)
	}
	response := postLogin(r, `{"username":"Ryan","password":"test-password"}`,
		"application/json", "true", "", "http://example.test/login")
	if response.Code != 500 || response.Body.String() != `{"error":"Login failed"}` || len(response.Result().Cookies()) != 0 {
		t.Fatalf("session failure must not return tokens or internal details: %d %s", response.Code, response.Body)
	}
}
